---
title: "Hosts Plots"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
library(lubridate)
library(robotstxt)
library(ggplot2)
library(ggmap)
library(RColorBrewer)
library(car)
library(scales)
knitr::opts_chunk$set(echo = TRUE)
```

```{r import-data}
# Read in full data sets
all_listings <- read_csv("airbnb_master.csv")
all_hosts <- read_csv("host_master.csv")
index_housing <- read_csv("housing_index.csv")
```


```{r scatter acceptance_rate vs response_rate}
# Pull needed vars
hosts_scatter <- all_hosts %>%
  select(id_host,
         host_response_proportion,
         host_acceptance_proportion,
         locale,
         host_listings_count_total) 

# Create plot object
acc_res_scatter <- ggplot(hosts_scatter, aes(x=host_response_proportion, y=host_acceptance_proportion)) +
  geom_hex(bins = 20,alpha = 0.9) + 
  scale_fill_gradient2(low="yellow",high="red") + 
  xlab("Host Response Rate") + 
  ylab("Host Acceptance Rate") + 
  ggtitle("Acceptance Rate vs Response Rate") +
  labs(fill = "# of Hosts")

# Print Object
acc_res_scatter
```


```{r scatter acceptance_rate vs listings_count}
# Prep data frame: convert id_host to factor var
hosts_scatter_b <- hosts_scatter %>%
  mutate(host_id = as.factor(id_host))
  filter(hosts_scatter, host_listings_count_total > 10)

# Create plot object
acc_listings_scatter <- ggplot(hosts_scatter_b, aes(x=host_listings_count_total, y=host_acceptance_proportion)) +
  geom_point(color = "Orange", alpha = 0.3) + 
  xlab("Host Number of Listings") + 
  ylab("Host Acceptance Rate") + 
  ggtitle("Acceptance Rate vs Number of Listings")

# Print Scatterplot
acc_listings_scatter
```


```{r bar graph monthly counts}
# Create data frame with counts of hosts joining each month
month_counts <- data.frame(table(all_hosts$month_host_joined))

# Create bar chart object
month_bar <- ggplot(data = month_counts, aes(x=Var1, y=Freq, fill = Var1)) +
  geom_col() + 
  xlab("Month Joined") +
  ylab("# of Hosts Joined") + 
  ggtitle("# of Hosts Joined by Month") + 
  theme(legend.position = "none")

# Print bar chart
month_bar
```

```{r host_since plot monthly Seasonality}
# Pull Vars
joined_since <- all_hosts %>%
  select(host_since, id_host)

# Reformat date joined to mmyy format
joined_since$host_since <- format(joined_since$host_since,"%m/%Y")

# Summarize counts
joined_summary <- data.frame(table(joined_since$host_since))

# Refactor vars
 joined_summary <- joined_summary %>%
   mutate(date = as.Date(Var1, format = "%m/%Y"))

# Create plot 
joined_time <- ggplot(joined_summary, aes(x = Var1, y = Freq, group = 1)) + 
  geom_point(stat='summary', fun.y=sum) + 
  stat_summary(fun = sum, geom = "line") +
  xlab("Date Joined") + 
  ylab("# of Hosts Joined ") 

# Print plot
joined_time
```


```{r host_since plot. Date vs join count}
# Pull vars
year_joined <- all_hosts %>%
  select(host_since, id_host)

# Reformat to just year
year_joined$host_since <- format(year_joined$host_since,"%Y")

# Count joiners for each year
year_summary <- data.frame(table(year_joined$host_since)) %>%
  rename("year" = Var1)

# Prep housing index data
index <- index_housing %>%
  mutate(year = as.factor(date))

combined <- merge(year_summary, index, by ="year") %>%
  select(-date)

coeff <- max(combined$value)/max(combined$Freq)

host_since_plot <- ggplot(combined, aes(x = year, group = 1)) + 
  geom_point(aes(y = Freq), col = "red") + 
  geom_point(aes(y = value / coeff), col = "blue") +
  scale_y_continuous(
    name = "Number of Hosts Joined",
    sec.axis = sec_axis(~.*coeff, name = "Housing Index $") 
  ) + 
  xlab("Year")

host_since_plot
```



























