---
title: "Listings Plots"
output: html_document
---

```{r setup, include=FALSE}
# Load Packages
library(tidyverse)
library(janitor)
library(lubridate)
library(robotstxt)
library(ggplot2)
library(ggmap)
library(RColorBrewer)
library(treemap)
library(leaflet)
knitr::opts_chunk$set(echo = TRUE)
```

```{r import-data}
# Load Data
all_listings <- read_csv("airbnb_master.csv")
all_hosts <- read_csv("host_master.csv")
```

```{r Rating vs RPM Scatter}
# Pull Vars
listing_scatter <- all_listings %>%
  select(listing_id,
         overall_rating,
         reviews_per_month,
         locale)

# Create Plot object
rating_rpm <- ggplot(listing_scatter, aes(x = reviews_per_month, y = overall_rating)) + 
  geom_point(col = "red", alpha = 0.2) + 
  xlab("Reviews Per Month") + 
  ylab("Overall Rating out of 5") + 
  ggtitle("Rating vs Reviews Per Month")

# Print plot
rating_rpm
```

```{r Violin plot of prices grouped by locale}
# Grab Data only needed for violin plot
violin_data <- all_listings %>%
  select(price_per_night, locale)
  
# Convert locale variable to factor variable
violin_data$locale <- as.factor(violin_data$locale)

# Get rid of outliers
Q1 <- quantile(violin_data$price_per_night, .25)
Q3 <- quantile(violin_data$price_per_night, .75)
IQR <- IQR(violin_data$price_per_night)

no_outliers <- subset(violin_data, violin_data$price_per_night > (Q1 - 1.5*IQR) & violin_data$price_per_night < (Q3 + 1.5*IQR))

# Reorder locales by median price
no_outliers %>%
  mutate(locale = fct_reorder(locale, price_per_night, .fun="median"))

# Create the violin plot
violin_plot <- ggplot(no_outliers, aes(x=reorder(locale, price_per_night), y=price_per_night, fill=locale)) + 
  geom_violin(trim=FALSE) +
  geom_boxplot(width=0.1, fill="white") + 
  labs(title="Pricing Distribution across Locales",x="Locale", y = "Price per Night") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  
# Print plot
violin_plot
```

```{r Treemap Prototype}
# Pull relevant vars
roomtype_counts <- all_listings %>%
  select(locale,
         room_type,
         bedrooms,
         beds)

# Filter by locale
roomtype_counts <- roomtype_counts %>%
  filter(locale == "Seattle")

# Count frequency by room type
roomtype_counts <- data.frame(table(roomtype_counts$room_type))

# Create Tree map
roomtype_map <- treemap(roomtype_counts,
                        index = "Var1",
                        vSize = "Freq", 
                        type = "index",
                        palette = "Set2")

#group <- c(rep("Austin",4),rep("Boston",4),rep("Chicago",4),rep("Denver",4),rep("Hawaii",4),rep("Los Angeles",4),rep("Nashville",4),
#rep("New Orleans",4),rep("New York",4),rep("San Diego",4),rep("San Francisco",4),rep("Seattle",4))

#subgroup <- c("Entire home/apt","Hotel room","Private room","Shared room")

#value = c(4295,6,683,60,
            #806,16,553,5,
            #2731,33,1060,54
            #1965,8,403,12
            #12662,70,1128,22
            #10120,66,3785,248
            #3760,47,388,7
            #3219,17,416,12
            #6961,108,5374,185
            #5350,7,1037,55
            #2061,44,1076,58
            #2086,453,16,0

# Print Tree map
roomtype_map
```

```{r TREEMAP}
# Create groups for Treemap
group = c(rep("Austin",4),
          rep("Boston",4),
          rep("Chicago",4),
          rep("Denver",4),
          rep("Hawaii",4),
          rep("Los Angeles",4),
          rep("Nashville",4),
          rep("New Orleans",4),
          rep("New York",4),
          rep("San Diego",4),
          rep("San Francisco",4),
          rep("Seattle",4))

# Create subgroup
subgroup <- c("Entire home/apt","Hotel room","Private room","Shared room",
              "Entire home/apt","Hotel room","Private room","Shared room",
              "Entire home/apt","Hotel room","Private room","Shared room",
              "Entire home/apt","Hotel room","Private room","Shared room",
              "Entire home/apt","Hotel room","Private room","Shared room",
              "Entire home/apt","Hotel room","Private room","Shared room",
              "Entire home/apt","Hotel room","Private room","Shared room",
              "Entire home/apt","Hotel room","Private room","Shared room",
              "Entire home/apt","Hotel room","Private room","Shared room",
              "Entire home/apt","Hotel room","Private room","Shared room",
              "Entire home/apt","Hotel room","Private room","Shared room",
              "Entire home/apt","Hotel room","Private room","Shared room")

# Initialize counts for each Locale/Subgroup
value = c(4295,6,683,60,
            806,16,553,5,
            2731,33,1060,54,
            1965,8,403,12,
            12662,70,1128,22,
            10120,66,3785,248,
            3760,47,388,7,
            3219,17,416,12,
            6961,108,5374,185,
            5350,7,1037,55,
            2061,44,1076,58,
            2086,453,16,0)

# Create dataframe for Treemap
data = data.frame(group,subgroup,value)

# Create Treemap
treemap(data,
        index = c("group","subgroup"),
        vSize = "value",
        type = "index",
        border.col = c("black","white"),
        border.lwds = c(7,2),
        overlap.labels = 1)
```

```{r treemap 2}
# Create groups
group1 = c(rep("Austin",4),
           rep("Boston",4),
           rep("Chicago",4),
           rep("Denver",4),
           rep("Hawaii",4),
           rep("Los Angeles",4))

# Create subgroups
subgroup1 <- c("Entire home/apt","Hotel room","Private room","Shared room",
              "Entire home/apt","Hotel room","Private room","Shared room",
              "Entire home/apt","Hotel room","Private room","Shared room",
              "Entire home/apt","Hotel room","Private room","Shared room",
              "Entire home/apt","Hotel room","Private room","Shared room",
              "Entire home/apt","Hotel room","Private room","Shared room")

# Create values for groups/subgroups
value1 = c(4295,6,683,60,
            806,16,553,5,
            2731,33,1060,54,
            1965,8,403,12,
            12662,70,1128,22,
            10120,66,3785,248)

# Push into dataframe
data1 = data.frame(group1,subgroup1,value1)

# Create Treemap
treemap(data1,
        index = c("group1","subgroup1"),
        vSize = "value1",
        type = "index",
        border.col = c("black","white"),
        border.lwds = c(1,1),
        overlap.labels = 1)
```

```{r Geospatial Map Prototype}
# Filter Points
filtered_points <- all_listings  %>%
  filter(locale == "New York") 

# Create map object
map <- leaflet(filtered_points) %>%
  addTiles() %>%
  setView(median(filtered_points$longitude), median(filtered_points$latitude), zoom = 11) %>%
  addCircles(~longitude, 
             ~latitude, 
             popup = filtered_points$listing_name,
             weight = 1, 
             radius=200,
             color="blue", 
             fillOpacity = 0.3)
```