---
title: "Word Cloud Plots"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
library(lubridate)
library(robotstxt)
library(ggplot2)
library(ggmap)
library(RColorBrewer)
library(car)
library(tm)
library(wordcloud)
library(wordcloud2)
knitr::opts_chunk$set(echo = TRUE)
```

```{r import-data}
all_listings <- read_csv("airbnb_master.csv")
all_hosts <- read_csv("host_master.csv")
```


```{r Wordcloud Description} 
#https://towardsdatascience.com/create-a-word-cloud-with-r-bde3e7422e8a
#prep data frame
listing_desc <- all_listings %>%
  select(listing_description)

listing_desc <- sample_n(listing_desc, 1000)

listing_desc

#create corpus
corp <- Corpus(VectorSource(listing_desc))


#clean corpus
corp <- corp %>%
  tm_map(removeNumbers) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace)
corp <- tm_map(corp, content_transformer(tolower))
corp <- tm_map(corp, removeWords, stopwords("english"))

#create doccument matrix for wordcloud
dtm <- TermDocumentMatrix(corp)
matrix <- as.matrix(dtm)
words <- sort(rowSums(matrix),decreasing=TRUE)
df <- data.frame(word = names(words),freq=words)

write_csv(df, "description_words.csv")

#set wordcloud seed for consistency
set.seed(53)

#create wordcloud
wordcloud(words = df$word, freq = df$freq, min.freq = 1, max.words=70, random.order=FALSE, rot.per=0.5,            colors=brewer.pal(8, "Dark2"))
```

```{r Description Barchart}
# Wrangling for bar chart frequency plot
desc_freq <- df[order(-df$freq),] %>%
  top_n(10)

# Create plot object
desc_bar <- ggplot(data = desc_freq, aes(x=reorder(word, freq), y=freq, fill = word)) +
  geom_col() +
  coord_flip()

# Print plot
desc_bar
```


```{r Wordcloud Name} 
#https://towardsdatascience.com/create-a-word-cloud-with-r-bde3e7422e8a
#prep data frame
listing_name <- all_listings %>%
  select(listing_name)

listing_name <- sample_n(listing_name, 1000)

listing_name

#create corpus
corp_name <- Corpus(VectorSource(listing_name))


#clean corpus
corp_name <- corp_name %>%
  tm_map(removeNumbers) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace)
corp_name <- tm_map(corp_name, content_transformer(tolower))
corp_name <- tm_map(corp_name, removeWords, stopwords("english"))

#create doccument matrix for wordcloud
dtm_name <- TermDocumentMatrix(corp_name)
matrix_name <- as.matrix(dtm_name)
words_name <- sort(rowSums(matrix_name),decreasing=TRUE)
df_name <- data.frame(word = names(words_name),freq=words_name)

write_csv(df_name, "name_words.csv")

#set wordcloud seed for consistency
set.seed(53)

#create wordcloud
wordcloud(words = df_name$word, freq = df_name$freq, min.freq = 1, max.words=70, random.order=FALSE, rot.per=0.3,            colors=brewer.pal(8, "Dark2"))
```


```{r Name Barchart}
# Wrangling for bar chart frequency plot
name_freq <- df_name[order(-df_name$freq),] %>%
  top_n(10)

# Create plot object
name_bar <- ggplot(data = name_freq, aes(x=reorder(word, freq), y=freq, fill = word)) +
  geom_col() +
  coord_flip()

# Print plot
name_bar
```











